Judo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('useris.urls')),
]

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

useris/urls.py
from django.urls import path
from .views import *

urlpatterns=[
    path('', index, name='index'),
]

useris/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.

class Season_tickets(models. Model):
    season_ticket=models.IntegerField(verbose_name='Абонемент')
    # validators=[MinValueValidator(1), MaxValueValidator(13),], 
    def __str__(self):
        return str(self.season_ticket)

    class Meta:
        verbose_name='абонемент'
        verbose_name_plural='Абонементы'

class Treners(models.Model):
    surname=models.CharField(max_length=50, verbose_name= 'Фамилия')
    name=models.CharField(max_length=50, verbose_name='Имя')
    middlename=models.CharField(max_length=50, verbose_name='Отчество')
    FIO_coach=models.CharField(max_length=100, db_index=True, verbose_name= 'ФИО тренера', blank=False)


    def __str__(self):
        return self.FIO_coach

    class Meta:
        verbose_name='тренер'
        verbose_name_plural='Тренеры'

class Groups(models.Model):
    name_section=models.CharField(max_length=50, verbose_name= 'Название секции')
    idgroup=models.IntegerField(verbose_name='Номер группы', db_index=True)
    quantity_in_week=models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(7)], verbose_name='Кол-во занятий/неделя')
    cost=models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(10000)], verbose_name='Стоимость')
    FIO_coach=models.ForeignKey(Treners, on_delete=models.PROTECT, null=True, verbose_name='ФИО тренера')

    def __str__(self):
        return self.name_section

    class Meta:
        verbose_name='группа'
        verbose_name_plural='Группы'
        ordering=['id']

class Children (models. Model):
    surname=models.CharField(max_length=50, verbose_name= 'Фамилия')
    name=models.CharField(max_length=50, verbose_name='Имя')
    middlename=models.CharField(max_length=50, verbose_name='Отчество')
    name_section=models.ForeignKey (Groups, on_delete=models.PROTECT, null=True, verbose_name='Группа')
    date_of_birth=models.DateField( null=True, verbose_name='Дата рождения')
    payment=models.BooleanField(default=False, verbose_name='Оплата')
    date_of_pay=models.DateField(null=True, verbose_name='Дата посл. оплаты')
    season_ticket=models.ForeignKey(Season_tickets, on_delete=models.PROTECT, null=True, verbose_name='Абонемент')
    comments=models.TextField(verbose_name='Комментарии', null=True, blank=True)

    # def get_idgroup(self):
    #     return "\n".join([p.groups for p in self.idgroup.all()])

    def __str__(self):
        return self.surname
        # , self.name, self.middlename

    class Meta:
        verbose_name='ребёнок'
        verbose_name_plural='Дети'
        # ordering=['-created_at', 'title']

class Userss(models.Model):
    surname=models.CharField(max_length=150, verbose_name='Фамилия')
    name=models.CharField(max_length=150, verbose_name='Имя')
    phone=models.CharField(max_length=20, verbose_name='Телефон')
    created=models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')
    
    def __str__(self):
        return str(self.name)

    class Meta:
        verbose_name='желающий'
        verbose_name_plural='Желающие'

useris/forms.py
from django import forms
from .models import Userss

class UsersForm(forms.ModelForm):
    class Meta:
        model = Userss
        fields = "__all__"

useris/views.py
from django.shortcuts import redirect, render
from .forms import UsersForm

# Create your views here.

def index(request):
    # fs=UsersForm()
    # modell=Userss()
    if request.method == 'POST':
        form = UsersForm(request.POST)
        print(form)
        if form.is_valid(): 
            user=form.save()
        # return HttpResponse('/thanks/')
        # return redirect(user)
        return render(request, 'index.html', )
    else:
        return render(request, 'index.html', )

# def index(request):
#     if request.method == 'POST':
#         form = UsersForm(request.POST)
#         if form.is_valid():
#             subject = "Пробное сообщение"
#             body = {
#                 'surname': form.cleaned_data['surname'],
#                 'name': form.cleaned_data['name'],
#                 'phone': form.cleaned_data['phone'],
#             }
#             message = "\n".join(body.values())
#             send_mail(subject, message, 
#                           'admin@example.com',
#                           ['mmk203@yandex.ru'])
#     return render(request, 'index.html', )

templates/i1.html
<section class="section-padding pb-0" id="reviews">
    <div class="container">
        <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-indicators">
                <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
                <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
            </div>
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img src="static/images/reviews/1.jpg" class="d-block w-100" alt="...">
                </div>
                <div class="carousel-item">
                    <img src="static/images/reviews/2.jpg" class="d-block w-100" alt="...">
                </div>
                <div class="carousel-item">
                    <img src="static/images/reviews/3.jpg" class="d-block w-100" alt="...">
                </div>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Next</span>
            </button>
        </div>
    </div>
</section>



<form method="post">
    {% csrf_token %}
    <!-- {{form.non_field.errors}} -->
    <div class="txt_field">
        <th><label for="id_name">Имя:</label></th>
        <span></span>
        <input type="text" name="name" maxlength="150" required id="id_name">
    </div>
    <div class="txt_field">
        <th><label for="id_phone">Телефон:</label></th>
        <span></span>
        <input type="text" name="phone" maxlength="20" required id="id_phone">
    </div>
    <button type="submit" id='addusers'>Отправить</button>
</form>

<form method="post">
    {% csrf_token %}
    <!-- {{form.non_field.errors}} -->
    <div class="txt_field">
        <input id="name" type="text" required>
        <span></span>
        <label>Имя</label>
    </div>
    <div class="txt_field">
        <input id="phone" type="text" required>
        <span></span>
        <label>Телефон</label>
    </div>
    <button type="submit" id='addusers'>Отправить</button>
</form>

<form method="post">
    {% csrf_token %}
    <!-- {{form.non_field.errors}} -->
    <tr>
        <th><label for="id_name">Имя:</label></th>
        <td>
            <ul class="errorlist">
                <li>Обязательное поле.</li>
            </ul>
            <input type="text" name="name" maxlength="150" required id="id_name">
        </td>
    </tr>
    <tr>
        <th><label for="id_phone">Телефон:</label></th>
        <td>
            <ul class="errorlist">
                <li>Обязательное поле.</li>
            </ul>
            <input type="text" name="phone" maxlength="20" required id="id_phone">
        </td>
    </tr>
    <button type="submit" id='addusers'>Отправить</button>
</form>

templates/q.html
<!DOCTYPE html>
<html>

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="static/css/style.css">
</head>

<body>

    <div class="slideshow-container">

        <div class="mySlides fade">
            <div class="numbertext">1 / 3</div>
            <img src="static/images/treners/aii.jpeg" style="width:100%">
            <div class="text">Caption Text</div>
        </div>

        <div class="mySlides fade">
            <div class="numbertext">2 / 3</div>
            <img src="static/images/treners/aai.jpeg" style="width:100%">
            <div class="text">Caption Two</div>
        </div>

        <div class="mySlides fade">
            <div class="numbertext">3 / 3</div>
            <img src="static/images/treners/alina.jpeg" style="width:100%">
            <div class="text">Caption Three</div>
        </div>

        <a class="prev" onclick="plusSlides(-1)">❮</a>
        <a class="next" onclick="plusSlides(1)">❯</a>

    </div>
    <br>

    <div style="text-align:center">
        <span class="dot" onclick="currentSlide(1)"></span>
        <span class="dot" onclick="currentSlide(2)"></span>
        <span class="dot" onclick="currentSlide(3)"></span>
    </div>

    <script>
        var slideIndex = 1;
        showSlides(slideIndex);

        function plusSlides(n) {
            showSlides(slideIndex += n);
        }

        function currentSlide(n) {
            showSlides(slideIndex = n);
        }

        function showSlides(n) {
            var i;
            var slides = document.getElementsByClassName("mySlides");
            var dots = document.getElementsByClassName("dot");
            if (n > slides.length) {
                slideIndex = 1
            }
            if (n < 1) {
                slideIndex = slides.length
            }
            for (i = 0; i < slides.length; i++) {
                slides[i].style.display = "none";
            }
            for (i = 0; i < dots.length; i++) {
                dots[i].className = dots[i].className.replace(" active", "");
            }
            slides[slideIndex - 1].style.display = "block";
            dots[slideIndex - 1].className += " active";
        }
    </script>

</body>

</html>